# Generated by Django 5.2.3 on 2025-07-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_imdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieImages',
            new_name='MovieImage',
        ),
    ]
